DATA_PATH = "model/data_model.pkl"
DATA_MAP_PATH = "model/data_map_model.pkl"
MODEL_PATH = "model/model.pkl"
SECOND_MODEL_PATH = "model/second_model.pkl"
THIRD_MODEL_PATH = "model/third_model.pkl"
BK_MODEL_PATH = "model/bk_model_1.pkl"
BK_SECOND_MODEL_PATH = "model/bk_second_model.pkl"
BK_THIRD_MODEL_PATH = "model/bk_third_model.pkl"
GP_MODEL_PATH = "model/gp_model.pkl"
IN_DIR = "img"
OUT_DIR = "noise_img"
TEST_DIR = "test_img"
OUT_MAP_DIR = "noise_map_img"
TEST_MAP_DIR = "test_map_img"
NOISE_PATH = "noise_img"
NOISE_MAP_PATH = "noise_map_img"
DETECTION_TRAIN_RESULT = "model/detection_train_result.pkl"


